### ISSUE TITLE
Rain/Snow particles appears underwater

### ISSUE THREAD

**Issue by rautars** [xeranas/weather_pack#2]

**Comment by Fixer-007** [comment]
In main brunch? I swore I've seen those particles under flowing water just now.

**Comment by rautars** [comment]
@Fixer-007 should be ok with water flows check (master branch).

**Comment by Fixer-007** [comment]
proof: https://i.imgur.com/HhSjKPM.png

**Comment by Fixer-007** [comment]
Let me try new version.
**Edit: fixed for now.**
