### ISSUE TITLE
Sometimes /set_weather X is not working

### ISSUE THREAD

**Issue by Fixer-007** [xeranas/weather_pack#3]
After lua crash I talked about earlier I restart the game again, thunder was present for some time but later cleared up. Tried to turn it back on, have no luck (rain, thunder, none) didn't help.

Version of mod = just now.

**Comment by rautars** [comment]
I am unable to reproduce this issue see my [comment ](https://github.com/minetest-mods/lightning/issues/2#issuecomment-228564513). Please see if this issue reproduces with default game (having only weather_pack and lightning as additional mods).

Please ensure that mod is loaded and privilege 'weather_manager' is granted for user before using chat commands.

**Comment by Fixer-007** [comment]
Use this https://github.com/minetest-mods/lightning/files/333268/etherial_modpack.zip to first reproduse lua strike function "crash" and after that start it again and wait until it clears up.

**Comment by rautars** [comment]
@Fixer-007 is this issue still exist? According your [comment](https://github.com/minetest-mods/lightning/issues/2#issuecomment-228573806) main issue was fixed.

**Comment by Fixer-007** [comment]
Hard to say, only time can tell, I will close it for now but reopen if it shows up again.
