### ISSUE TITLE
Rainy night is much brighter than clear night

### ISSUE THREAD

**Issue by Fixer-007** [xeranas/weather_pack#4]
You can see it for yourself when you `/set_weather rain` at 0:00, compare it with `none` weather. I think fog blending should be different at night, fog must be dark at this time.
If it is RGB values, make it close to night but more greyish.
I've looked at this, changed values.

```
rain.set_sky_box = function(player)
  if (minetest.get_timeofday() < 0.8) then
    player:set_sky({r=65, g=80, b=10}, "plain", nil)
  else
    player:set_sky({r=10, g=10, b=15}, "plain", nil)
  end
end
```

r=6, g=8, b=1 is very good for night. 
**However, I feel very suspicious about this function**, about (minetest.get_timeofday() < 0.8) part, I was experimenting with sky colour at various times and it seems broken for me :/ 
Please investigate this part, example of brokenness: https://i.imgur.com/NTW15yW.png (8:05) (if i reset it to none and back to rain it goes back to normal), so fog problems are here and need rework.

**Comment by rautars** [comment]
Actually its not a 'fog' but sky itself. If I could use transparent image it would be much cleaner solution as it is right now. But seems [2729](https://github.com/minetest/minetest/issues/2729) is nowere to go.

As you can see currently only two sky colors are used for rainy weather. I could not find any better approach I will add more variants and make call to udate skybox.

**Comment by Fixer-007** [comment]
Night sky colour looks good but daylight looks somewhat artificial (greenish blue tint (malachitish)), at least on my monitor, you need to reduce green part.

**Comment by rautars** [comment]
@Fixer-007 could be. I will review colors. I also accepting suggestions for color_table rgb variants if you have any.

**Comment by Fixer-007** [comment]
Fixed :+1:
